(ns trrnt.client-names)

;; from list of known client names in https://wiki.theory.org/BitTorrentSpecification
(def known-bt-client-names {"7T" "aTorrent for Android"
                   "AB" "AnyEvent::BitTorrent"
                   "AG" "Ares"
                   "A"' "Ares"
                   "AR" "Arctic"
                   "AV" "Avicora"
                   "AT" "Artemis"
                   "AX" "BitPump"
                   "AZ" "Azureus"
                   "BB" "BitBuddy"
                   "BC" "BitComet"
                   "BE" "Baretorrent"
                   "BF" "Bitflu"
                   "BG" "BTG (uses Rasterbar libtorrent)"
                   "BL" "BitBlinder"
                   "BP" "BitTorrent Pro (Azureus + spyware)"
                   "BR" "BitRocket"
                   "BS" "BTSlave"
                   "BT" "BBtor"
                   "BW" "BitWombat"
                   "BX" "~Bittorrent X"
                   "CD" "Enhanced CTorrent"
                   "CT" "CTorrent"
                   "DE" "DelugeTorrent"
                   "DP" "Propagate Data Client"
                   "EB" "EBit"
                   "ES" "electric sheep"
                   "FC" "FileCroc"
                   "FT" "FoxTorrent"
                   "FX" "Freebox BitTorrent"
                   "GS" "GSTorrent"
                   "HK" "Hekate"
                   "HL" "Halite"
                   "HM" "hMule (uses Rasterbar libtorrent)"
                   "HN" "Hydranode"
                   "IL" "iLivid"
                   "JS" "Justseed.it client"
                   "JT" "JavaTorrent"
                   "KG" "KGet"
                   "KT" "KTorrent"
                   "LC" "LeechCraft"
                   "LH" "LH-ABC"
                   "LP" "Lphant"
                   "LT" "libtorrent"
                   "lt" "libTorrent"
                   "LW" "LimeWire"
                   "MK" "Meerkat"
                   "MO" "MonoTorrent"
                   "MP" "MooPolice"
                   "MR" "Miro"
                   "MT" "MoonlightTorrent"
                   "NB" "Net::BitTorrent"
                   "NX" "Net Transport"
                   "OS" "OneSwarm"
                   "OT" "OmegaTorrent"
                   "PB" "Protocol::BitTorrent"
                   "PD" "Pando"
                   "PT" "PHPTracker"
                   "qB" "qBittorrent"
                   "QD" "QQDownload"
                   "QT" "Qt 4 Torrent example"
                   "RT" "Retriever"
                   "RR" "trrnt.clj"
                   "RZ" "RezTorrent"
                   "S" "Shareaza alpha/beta"
                   "SB" "~Swiftbit"
                   "SD" "Thunder (aka XùnLéi)"
                   "SM" "SoMud"
                   "SP" "BitSpirit"
                   "SS" "SwarmScope"
                   "ST" "SymTorrent"
                   "st" "sharktorrent"
                   "SZ" "Shareaza"
                   "TB" "Torch"
                   "TE" "terasaur Seed Bank"
                   "TL" "Tribler (versions >= 6.1.0)"
                   "TN" "TorrentDotNET"
                   "TR" "Transmission"
                   "TS" "Torrentstorm"
                   "TT" "TuoTu"
                   "TV" "Tulva"
                   "UL" "uLeecher!"
                   "UM" "µTorrent for Mac"
                   "UT" "µTorrent"
                   "VG" "Vagaa"
                   "WT" "BitLet"
                   "WW" "WebTorrent"
                   "WY" "FireTorrent"
                   "XF" "Xfplay"
                   "XL" "Xunlei"
                   "XS" "XSwifter"
                   "XT" "XanTorrent"
                   "XX" "Xtorrent"
                   "ZT" "ZipTorrent"})
